IEMOCAP_PATH_TO_WAVS = 'C:\\Users\\Artem\\Documents\\Projects\\SER\\datasets\\iemocap'
# IEMOCAP_PATH_TO_WAVS = 'E:\\Projects\\emotion_recognition\\knn_svm\\datasets\\iemocap_audios'
PATH_TO_PICKLE = 'datasets'
# IEMOCAP_PATH_TO_WAVS = 'datasets'
# IEMOCAP_PATH_TO_WAVS = 'datasets\\iemocap'