from datasets import *


iemocap_original_256_noprep_zeropad = IemocapDataset(
    pickle_folder=PATH_TO_PICKLE,
    wavs_folder=IEMOCAP_PATH_TO_WAVS,
    base_name='IEMOCAP',
    label_type='original',
    spectrogram_shape=256,
    preprocessing='false',
    padding='zero')
iemocap_original_256_prep_zeropad = IemocapDataset(
    pickle_folder=PATH_TO_PICKLE,
    wavs_folder=IEMOCAP_PATH_TO_WAVS,
    base_name='IEMOCAP',
    label_type='original',
    spectrogram_shape=256,
    preprocessing='true',
    padding='zero')
iemocap_original_256_noprep_repeat = IemocapDataset(
    pickle_folder=PATH_TO_PICKLE,
    wavs_folder=IEMOCAP_PATH_TO_WAVS,
    base_name='IEMOCAP',
    label_type='original',
    spectrogram_shape=256,
    preprocessing='false',
    padding='repeat')
iemocap_original_256_prep_repeat = IemocapDataset(
    pickle_folder=PATH_TO_PICKLE,
    wavs_folder=IEMOCAP_PATH_TO_WAVS,
    base_name='IEMOCAP',
    label_type='original',
    spectrogram_shape=256,
    preprocessing='true',
    padding='repeat')

iemocap_four_256_noprep_zeropad = IemocapDataset(
    pickle_folder=PATH_TO_PICKLE,
    wavs_folder=IEMOCAP_PATH_TO_WAVS,
    base_name='IEMOCAP',
    label_type='four',
    spectrogram_shape=256,
    preprocessing='false',
    padding='zero')
iemocap_four_256_prep_zeropad = IemocapDataset(
    pickle_folder=PATH_TO_PICKLE,
    wavs_folder=IEMOCAP_PATH_TO_WAVS,
    base_name='IEMOCAP',
    label_type='four',
    spectrogram_shape=256,
    preprocessing='true',
    padding='zero')
iemocap_four_256_noprep_repeat = IemocapDataset(
    pickle_folder=PATH_TO_PICKLE,
    wavs_folder=IEMOCAP_PATH_TO_WAVS,
    base_name='IEMOCAP',
    label_type='four',
    spectrogram_shape=256,
    preprocessing='false',
    padding='repeat')
iemocap_four_256_prep_repeat = IemocapDataset(
    pickle_folder=PATH_TO_PICKLE,
    wavs_folder=IEMOCAP_PATH_TO_WAVS,
    base_name='IEMOCAP',
    label_type='four',
    spectrogram_shape=256,
    preprocessing='true',
    padding='repeat')